### ISSUE TITLE
Bug (probably) when you win very fast in 2 Bit difficulty

### ISSUE THREAD

**Issue by JostP** [marvinborner/BinaryFunSFOS#1]
Hello,
Great game.
I think I found a bug in 2 Bit difficulty. When you win very fast (less than 1 sec) this happens:

![Posnetek_zaslona_20200418_001](https://user-images.githubusercontent.com/47271658/79639160-1968f400-818a-11ea-88e3-d3d1118b9639.png)

And when I try to check Leaderboard...

![Posnetek_zaslona_20200418_002](https://user-images.githubusercontent.com/47271658/79639173-4ae1bf80-818a-11ea-912a-6168ba6e35ad.png)

Leaderboard had worked before I got weird result, maybe your website crash. This has happened twice. I use Sony Xperia X. 

EDIT: no idea why this screenshots are so big

**Comment by marvinborner** [comment]
Haha sorry for the late response, I never got to fix it unfortunately. I don't use Sailfish OS anymore and I don't even have the source code of the server anymore :/

Well, I'll close this. But thanks for having used my app :)
